# Hyperparameters
TMIN = 0.0 # ok
TMAX = 3.0 # ok
L_FREQ = 0.5 # ok
H_FREQ = 40. # ok
BASE_SAMPLES_PER_SECONDE = 160
TARGET_SAMPLES = BASE_SAMPLES_PER_SECONDE * (TMAX - TMIN)
MOTOR_LABELS = ['C3', 'Cz', 'C4']
N_COMPONENTS = 4
MODEL_DIR = 'models'
# DATA
RUNS_LEFT_RIGHT = [3, 4, 7, 8, 11, 12]
RUNS_FIST_FEET = [5 , 6, 9, 10, 13, 14]